services:
  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

  app:
    build: ./app
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
